apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: ap-south-1

vpc:
  id: vpc-0c6062e114e8f5930
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-0fd3c7671861bf4d8
      my-new-stack-PublicSubnet02:
        id: subnet-06f9a19371a0b64a2

nodeGroups:
  - name: EKS-public-workers
    securityGroups:
      withShared: true
      withLocal: true
      attachIDs: ["sg-0cb244f616b0c18ce"]
    instanceType: t2.medium
    desiredCapacity: 2
